apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: benchmark-synth-
spec:
  serviceAccountName: workflow
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi
  entrypoint: main
  arguments:
    parameters:
      - name: val_sample
        value: 30000
      - name: final_size
        value: 50000
      - name: preprocessed
        value: true
      - name: synth_split
        value: 0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
      - name: synth_name
        value: naive_exhaustive,retext1_distrib,retext1_exhaustive
      - name: embedding_dim
        value: 256
      - name: num_epochs
        value: 15
      - name: lr
        value: 5e-4
      - name: patience_early_stopping
        value: 2
  templates:
    - name: main
      inputs:
        parameters:
        - name: val_sample
        - name: final_size
        - name: preprocessed
        - name: synth_split
        - name: synth_name
        - name: embedding_dim
        - name: num_epochs
        - name: lr
        - name: patience_early_stopping
      container:
        image: inseefrlab/onyxia-vscode-pytorch:py3.13.5-gpu
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4000m
            memory: 100Gi
          requests:
              nvidia.com/gpu: 1  # Add GPU to requests too
              cpu: 300m
              memory: 30Gi
        command: ["/bin/bash", -c]
        args:
          - |
            set -e  # Exit on error
            set -x  # Print commands for debugging

            # Clone repository and submodules
            git clone -b main https://github.com/mateomorin/ttc-training.git
            cd ttc-training/

            # Setup
            uv sync --extra gpu

            # Run MLflow experiment
            uv run src/training/benchmark_synth.py -m \
                training_config.accelerator=cuda \
                input_data.val_sample={{inputs.parameters.val_sample}} \
                input_data.final_size={{inputs.parameters.final_size}} \
                input_data.preprocessed={{inputs.parameters.preprocessed}} \
                input_data.synth_split={{inputs.parameters.synth_split}} \
                input_data.synth_name={{inputs.parameters.synth_name}} \
                model.embedding_dim={{inputs.parameters.embedding_dim}} \
                training_config.num_epochs={{inputs.parameters.num_epochs}} \
                training_config.lr={{inputs.parameters.lr}} \
                training_config.patience_early_stopping={{inputs.parameters.patience_early_stopping}}

        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-read-only
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://minio.lab.sspcloud.fr
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_URI 
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_PASSWORD 
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-mlflow-creds
                key: MLFLOW_TRACKING_USERNAME 
          - name: CUBLAS_WORKSPACE_CONFIG       # For deterministic parallel computing
            value: ":4096:8"